[package]
name = "sws-lua"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
crossbeam-channel = "0.5"
csv = "1"
mlua = { version = "0.7", features = ["luajit", "vendored", "serialize"] }
once_cell = "1"
serde = { version = "1", features = ["derive"] }
sws-scraper = { path = "../sws-scraper" }
sws-crawler = { path = "../sws-crawler" }
