[package]
name = "sws-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
cssparser = "0.27"
html5ever = "0.25"
selectors = "0.22"
smallvec = "1"
sws-tree = { path = "../sws-tree" }
tendril = "0.4"