[package]
name = "sws-scraper"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bitflags = "1"
cssparser = "0.28"
html5ever = "0.26"
selectors = "0.23"
smallvec = "1"
string_cache = "0.8"
sws-tree = { path = "../sws-tree" }
tendril = "0.4"
