[package]
name = "sws-scraper"
version = "0.2.4"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
cssparser = "0.31"
html5ever = "0.26"
selectors = "0.25"
sws-tree = { path = "../sws-tree", version = "1" }
tendril = "0.4"
