[package]
name = "sws"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
# csv = "1"
# serde = { version = "1", features = ["derive"] }
# serde_json = "1"
structopt = "0.3"
sws-crawler = { path = "../sws-crawler" }
sws-lua = { path = "../sws-lua" }
tokio = { version = "1", features = ["full"] }
